version: 0.2

# docker image build; environment variables set in console build project settting
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - AI_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AI_IMAGE_REPO_NAME
      - FE_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FE_IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the AI Docker image...
      - docker build -t $AI_REPOSITORY_URI:latest .
      - docker tag $AI_REPOSITORY_URI:latest $AI_REPOSITORY_URI:$IMAGE_TAG
       - echo Building the FrontEnd Docker image...
      - docker build -t $FE_REPOSITORY_URI:latest .
      - docker tag $FE_REPOSITORY_URI:latest $FE_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the AI Docker image...
      - docker push $AI_REPOSITORY_URI:latest
      - docker push $AI_REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing the FrontEnd Docker image...
      - docker push $FE_REPOSITORY_URI:latest
      - docker push $FE_REPOSITORY_URI:$IMAGE_TAG      
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$AI_REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "$FE_REPOSITORY_URI" "$FE_REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
