default_agent: strands_agent
agents:
  multi_strands:
    name: multi_strands
    language: python
    node_version: '20'
    entrypoint: /Users/danielmartinez/Desktop/AWS/github/devops/agentcore/strands_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/danielmartinez/Desktop/AWS/github/devops/agentcore
    aws:
      execution_role: arn:aws:iam::521575032089:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-d1c2a231c1
      execution_role_auto_create: false
      account: '521575032089'
      region: us-west-2
      ecr_repository: 521575032089.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-multi_strands
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  strands_agent:
    name: strands_agent
    language: python
    node_version: '20'
    entrypoint: /Users/danielmartinez/Desktop/AWS/github/devops/agentcore/strands_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/danielmartinez/Desktop/AWS/github/devops/agentcore
    aws:
      execution_role: arn:aws:iam::521575032089:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-6a6a8eb7be
      execution_role_auto_create: false
      account: '521575032089'
      region: us-west-2
      ecr_repository: 521575032089.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-strands_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: strands_agent-Ejaldy7YlE
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:521575032089:runtime/strands_agent-Ejaldy7YlE
      agent_session_id: 2b7ac0af-b7b9-42a2-8f10-d006d16b0dd0
    codebuild:
      project_name: bedrock-agentcore-strands_agent-builder
      execution_role: arn:aws:iam::521575032089:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-6a6a8eb7be
      source_bucket: bedrock-agentcore-codebuild-sources-521575032089-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
