AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for WebServer with Security Group and EC2 Instance

Resources:
  DemoEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t3.micro"
      ImageId: ami-00a8151272c45cd8e
      Tags:
        - Key: Name
          Value: Helloworld
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install wget git -y
          amazon-linux-extras install docker
          service docker start
          usermod -a -G docker ec2-user
