AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for WebServer with Security Group and EC2 Instance

Resources:
  DemoEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: ami-00a8151272c45cd8e
      Tags:
        - Key: Name
          Value: Helloworld
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install wget git -y
          yum install docker -y
          service docker start
          usermod -a -G docker ec2-user
          reboot

CFN/YAML

---
# Step 1: Create a Security Group
Resources:
  LaunchWizard2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: launch-wizard-2
      GroupDescription: launch-wizard-2 created 2026-01-22T06:48:20.034Z
      VpcId: vpc-0ff64a162a69f3f8b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

# Step 2: Create an EC2 Instance
Resources:
  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00a8151272c45cd8e
      InstanceType: t2.micro
      KeyName: ec2-user
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install wget git -y
          amazon-linux-extras install docker
          service docker start
          usermod -a -G docker ec2-user
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref LaunchWizard2SecurityGroup
      CreditSpecification:
        CPUCredits: standard
      Tags:
        - Key: Name
          Value: demo
      MetadataOptions:
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 2
        HttpTokens: required
      PrivateDnsNameOptions:
        HostnameType: ip-name
        EnableResourceNameDnsARecord: true
        EnableResourceNameDnsAAAARecord: false

Reasoning:

1) Libraries and their versions used: AWS CloudFormation, AWS::EC2::SecurityGroup, AWS::EC2::Instance
2) AWS resources impacted: AWS::EC2::SecurityGroup, AWS::EC2::Instance
3) AWS actions performed: Create a Security Group, Create an EC2 Instance
4) Explanation:
   - The YAML creates a Security Group named 'launch-wizard-2' with a description and VPC ID specified in the CLI commands. It also allows inbound traffic on ports 22 (SSH) and 443 (HTTPS) from any IP address (0.0.0.0/0).
   - The YAML then creates an EC2 Instance with the specified AMI ID, instance type, key pair, and user data. It associates the instance with the created Security Group and enables public IP assignment.
   - The instance is configured with standard CPU credits, a Name tag, metadata options for HTTP endpoint and tokens, and private DNS name options asd in the CLI commands.